# Generated by Django 4.0.5 on 2022-07-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('position', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('contact_no', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('facebook', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('skype', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('resume_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
