# Generated by Django 4.0.5 on 2022-07-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(blank=True)),
                ('project_completed', models.IntegerField(blank=True)),
                ('reveiw', models.IntegerField(blank=True)),
                ('running_project', models.IntegerField(blank=True)),
            ],
        ),
    ]
