# Generated by Django 4.0.5 on 2022-07-30 19:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testimonial_pro_pic_url_alter_testimonial_pro_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('copy_right', models.CharField(max_length=255)),
                ('banner_bg', models.FileField(upload_to='site/')),
                ('skill_bg', models.FileField(upload_to='site/')),
                ('summery_bg', models.FileField(upload_to='site/')),
                ('testimonial_bg', models.FileField(upload_to='site/')),
                ('contact_bg', models.FileField(upload_to='site/')),
            ],
        ),
        migrations.CreateModel(
            name='WonerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
