# Generated by Django 4.0.5 on 2022-07-30 19:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesetting_wonertitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
