# Generated by Django 4.0.5 on 2022-07-31 20:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_sitesetting_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 2, 42, 40, 996788), null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='site/'),
            preserve_default=False,
        ),
    ]
